# This file describes the GitHub Actions workflow for continuous integration of Spike.
#
# See
# https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions
# for API reference documentation on this file format.

name: Continuous Integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-13]
    name: Test Spike build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          # checkout full tree
          fetch-depth: 0

      - uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes
          nix_path: nixpkgs=channel:nixos-25.05
      - run: |
          for commit in $(git rev-list origin/master..HEAD | tac); do
            nix build
            ci-tests/test-spike
          done
